---

- name: "Create Openshift Config Maps"
  include_tasks: process-configmaps.yml
  with_items:
    - "{{ configMaps | filter_applier_items(filter_tags) | default([]) }}"
  loop_control:
    loop_var: configmap
  when:
    - configMaps is defined
