---

- name: "debug cm data"
  debug:
    msg: "**** CM DATA {{ configmap }}"

- name: "Create OpenShift ConfigMap ('{{ entry.object }}') - based on individual files"
  include_tasks: process-entry.yml

