---

- name: "Create OpenShift ConfigMap ('{{ entry.object }}') - based on individual files"
  include_tasks: process-entry.yml
  with_items:
    - "{{ configs.configmaps | default([]) }}"
  loop_control:
    loop_var: content

