---

- name: Debug
  debug:
     msg: "ConfigMap content: {{ configmap }}"

- name: "Set default values"
  set_fact:
    object_name: "{{ configmap.name }}"
    target_namespace: ''
    properties_file: "{{ configmap.properties_file | default('') }}"
    destination: "{{ configmap.destination | default('') }}"
    params: "{{ configmap.params | default('') }}"
    params_from_vars: "{{ configmap.params_from_vars | default({}) }}"
    oc_ignore_unknown_parameters: "{{ configmap.ignore_unknown_parameters | default(oc_ignore_unknown_parameters) }}"
    no_log: False

- name: "Set the target namespace option if supplied"
  set_fact:
    target_namespace: "-n {{ configmap.namespace }}"
  when:
    - configmap.namespace is defined

- name: "{{ oc_action | capitalize }} OpenShift objects based on static files for '{{ entry.object }} : {{ configmaps.name | default(file | basename) }}'"
  command: >
    oc create configmap {{object_name }} \
       {{ target_namespace }} \
       --from-file {{ properties_file }} \
       --dry-run=true -o yaml
  no_log: "{{ no_log }}"
  register: command_result
  failed_when:
    - command_result.rc != 0
    - "'AlreadyExists' not in command_result.stderr"

- name: "debug"
  debug: "command_result: {{ command_result }}"